### ISSUE TITLE
<html> tags missing

### ISSUE THREAD

**Issue by DennisDobslaf** [jzbick/aboveclouds#1]
https://github.com/jzbick/aboveclouds/blob/master/main/index.php

< !DOCTYPE html>
< html lang="de">

< /html>
(Leerzeichen müssen entfernt werden)

Fehlt in einigen PHP Skripten ;-)
Könnte zu Fehlern in der Darstellung und bei Javascript führen.

**Comment by jzbick** [comment]
Habe ich korrigiert, vielen Dank!
